local Rule = require('nvim-autopairs.rule')
local npairs = require('nvim-autopairs')
npairs.setup({ map_cr = true })
npairs.add_rule(Rule("$$", "$$", { "markdown", "quarto", "tex" }))
npairs.add_rule(Rule("```", "```", { "markdown", "quarto" }))
npairs.add_rule(Rule("_", "_", { "markdown", "quarto" }))
npairs.add_rule(Rule("*", "*", { "markdown", "quarto" }))
npairs.add_rule(Rule("~", "~", { "markdown", "quarto" }))
npairs.add_rule(Rule('"""', '"""', 'python'))
npairs.add_rule(Rule("%", "%", "htmldjango"))
npairs.add_rule(Rule("'", "'", "*"))
